export const fld = {
  BOARD_COUNT: 'Board count',
  BOARD_WIDTH: 'Board width',
  DATE_ENDED: 'Date ended',
  DATE_ENDED_GANTT: 'Date ended (Gantt)',
  DATE_STAGED: 'Date staged',
  DATE_STARTED: 'Date started',
  DATE_STARTED_GANTT: 'Date started (Gantt)',
  DIAMETER: 'Diameter',
  HISTORY: 'History',
  LENGTH: 'Length',
  LOG: 'Log',
  LOG_ID: 'Log ID',
  NAME: 'Name',
  NUM_BOARDS: '# Boards',
  NUM_LOGS: '# Logs',
  NUM_SLABS: '# Slabs',
  PRODUCT: 'Product',
  PRODUCT_ID: 'Product ID',
  SPECIES: 'Species',
  SLAB_ID: 'Slab ID',
  SLAB_MAX_WIDTH: 'Slab max width',
  SLAB_MIN_WIDTH: 'Slab min width',
  STAGE: 'Stage',
  SYMBOL: 'SYMBOL',
  THICKNESS: 'Thickness',
  TREE: 'Tree',
  TREE_ID: 'Tree ID',
  TYPE: 'Type'
};

export const tbl = {
  HISTORY: 'History',
  LOGS: 'Logs',
  LOCATIONS: 'Locations',
  PRODUCTS: 'Products',
  STAGES: 'Stages',
  SPECIES: 'Species',
  TREES: 'Trees'
};
